name: 'versioning-toolkit'
description: 'Set of helpers for versioning'
author: 'Shoreline.io'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  actionName:
    description: 'action name'
    required: true
  prefix:
    description: 'prefix to filter tags'
    required: false
  pushTag:
    description: 'push tag or not'
    required: false
    default: 'false'

